
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class EspecialidadesMedicas extends javax.swing.JFrame {

    /**
     * Creates new form EspecialidadesMedicas
     */
    public EspecialidadesMedicas() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAdministrativo = new javax.swing.JMenu();
        mnuItemAltasAlumnado = new javax.swing.JMenuItem();
        mnuItemBajasAlumnado = new javax.swing.JMenuItem();
        mnuItemModAlumnado = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemAltasDocente = new javax.swing.JMenuItem();
        menuItemBajasDocente = new javax.swing.JMenuItem();
        mnuItemModDocente = new javax.swing.JMenuItem();
        mnuAlumnos = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuItemAltasMaterias = new javax.swing.JMenuItem();
        mnuBajasMaterias = new javax.swing.JMenuItem();
        mnuItemBecas = new javax.swing.JMenuItem();
        mnuEstudios = new javax.swing.JMenu();
        mnuItemPlanEstudios = new javax.swing.JMenuItem();
        mnuDatosPersonales = new javax.swing.JMenu();
        mnuItemProfesional = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        menuItemConsultasDocente = new javax.swing.JMenuItem();
        menuItemPerfilDocente = new javax.swing.JMenuItem();
        menuItemConsultaAlumnado = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        mnuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividad Complementaria");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOEXACTAS.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 380, 330));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 255));

        mnuAdministrativo.setBackground(new java.awt.Color(0, 0, 204));
        mnuAdministrativo.setForeground(new java.awt.Color(0, 0, 255));
        mnuAdministrativo.setText("Administrativo");

        mnuItemAltasAlumnado.setForeground(new java.awt.Color(0, 0, 255));
        mnuItemAltasAlumnado.setText("Altas Alumnado");
        mnuItemAltasAlumnado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAltasAlumnadoActionPerformed(evt);
            }
        });
        mnuAdministrativo.add(mnuItemAltasAlumnado);

        mnuItemBajasAlumnado.setForeground(new java.awt.Color(0, 0, 255));
        mnuItemBajasAlumnado.setText("Bajas Alumnado");
        mnuItemBajasAlumnado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemBajasAlumnadoActionPerformed(evt);
            }
        });
        mnuAdministrativo.add(mnuItemBajasAlumnado);

        mnuItemModAlumnado.setForeground(new java.awt.Color(0, 0, 255));
        mnuItemModAlumnado.setText("Modificaciones Alumnado");
        mnuItemModAlumnado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemModAlumnadoActionPerformed(evt);
            }
        });
        mnuAdministrativo.add(mnuItemModAlumnado);
        mnuAdministrativo.add(jSeparator1);

        menuItemAltasDocente.setForeground(new java.awt.Color(0, 0, 255));
        menuItemAltasDocente.setText("Altas Docente");
        menuItemAltasDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAltasDocenteActionPerformed(evt);
            }
        });
        mnuAdministrativo.add(menuItemAltasDocente);

        menuItemBajasDocente.setForeground(new java.awt.Color(0, 0, 255));
        menuItemBajasDocente.setText("Bajas Docente");
        menuItemBajasDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBajasDocenteActionPerformed(evt);
            }
        });
        mnuAdministrativo.add(menuItemBajasDocente);

        mnuItemModDocente.setForeground(new java.awt.Color(0, 0, 255));
        mnuItemModDocente.setText("Modificaciones Docente");
        mnuItemModDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemModDocenteActionPerformed(evt);
            }
        });
        mnuAdministrativo.add(mnuItemModDocente);

        jMenuBar1.add(mnuAdministrativo);

        mnuAlumnos.setForeground(new java.awt.Color(0, 0, 255));
        mnuAlumnos.setText("Alumnos");
        mnuAlumnos.add(jSeparator2);

        mnuItemAltasMaterias.setForeground(new java.awt.Color(0, 0, 255));
        mnuItemAltasMaterias.setText("AltasMaterias");
        mnuItemAltasMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAltasMateriasActionPerformed(evt);
            }
        });
        mnuAlumnos.add(mnuItemAltasMaterias);

        mnuBajasMaterias.setForeground(new java.awt.Color(0, 0, 255));
        mnuBajasMaterias.setText("BajasMaterias");
        mnuBajasMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBajasMateriasActionPerformed(evt);
            }
        });
        mnuAlumnos.add(mnuBajasMaterias);

        mnuItemBecas.setForeground(new java.awt.Color(0, 0, 255));
        mnuItemBecas.setText("Becas");
        mnuItemBecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemBecasActionPerformed(evt);
            }
        });
        mnuAlumnos.add(mnuItemBecas);

        jMenuBar1.add(mnuAlumnos);

        mnuEstudios.setForeground(new java.awt.Color(0, 0, 255));
        mnuEstudios.setText("Estudios");

        mnuItemPlanEstudios.setForeground(new java.awt.Color(0, 0, 255));
        mnuItemPlanEstudios.setText("Plan de Estudios");
        mnuItemPlanEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPlanEstudiosActionPerformed(evt);
            }
        });
        mnuEstudios.add(mnuItemPlanEstudios);

        jMenuBar1.add(mnuEstudios);

        mnuDatosPersonales.setForeground(new java.awt.Color(0, 0, 255));
        mnuDatosPersonales.setText("Datos Personales");

        mnuItemProfesional.setForeground(new java.awt.Color(0, 0, 255));
        mnuItemProfesional.setText("Profesional");
        mnuItemProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemProfesionalActionPerformed(evt);
            }
        });
        mnuDatosPersonales.add(mnuItemProfesional);

        jMenuBar1.add(mnuDatosPersonales);

        mnuConsultas.setForeground(new java.awt.Color(0, 0, 255));
        mnuConsultas.setText("Consultas");

        menuItemConsultasDocente.setForeground(new java.awt.Color(0, 0, 255));
        menuItemConsultasDocente.setText("Consulta Docentes");
        menuItemConsultasDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultasDocenteActionPerformed(evt);
            }
        });
        mnuConsultas.add(menuItemConsultasDocente);

        menuItemPerfilDocente.setForeground(new java.awt.Color(0, 0, 255));
        menuItemPerfilDocente.setText("Perfil Docentes");
        menuItemPerfilDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPerfilDocenteActionPerformed(evt);
            }
        });
        mnuConsultas.add(menuItemPerfilDocente);

        menuItemConsultaAlumnado.setForeground(new java.awt.Color(0, 0, 255));
        menuItemConsultaAlumnado.setText("Consulta Alumnado");
        menuItemConsultaAlumnado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaAlumnadoActionPerformed(evt);
            }
        });
        mnuConsultas.add(menuItemConsultaAlumnado);

        jMenuBar1.add(mnuConsultas);

        menuSalir.setForeground(new java.awt.Color(0, 0, 255));
        menuSalir.setText("Salir");

        mnuItemSalir.setText("Salir");
        mnuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSalirActionPerformed(evt);
            }
        });
        menuSalir.add(mnuItemSalir);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemAltasMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAltasMateriasActionPerformed
        //Abre el formulario AltasCalificacionesAlumnos
        new AltasCalificaciones().setVisible(true);
    }//GEN-LAST:event_mnuItemAltasMateriasActionPerformed

    private void mnuBajasMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBajasMateriasActionPerformed
        //Abre el formulario BajaMaterias
        new BajaMaterias().setVisible(true);
    }//GEN-LAST:event_mnuBajasMateriasActionPerformed

    private void mnuItemBecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBecasActionPerformed
        //Abre el formulario Becas
       new Becas().setVisible(true);
    }//GEN-LAST:event_mnuItemBecasActionPerformed

    private void mnuItemPlanEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPlanEstudiosActionPerformed
        //Abre el formulario Plan de estudios
       new PlanEstudios().setVisible(true);
    }//GEN-LAST:event_mnuItemPlanEstudiosActionPerformed

    private void mnuItemProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemProfesionalActionPerformed
        //Abre el formulario Datos profesionales
        new Profesional().setVisible(true);
    }//GEN-LAST:event_mnuItemProfesionalActionPerformed

    private void menuItemConsultasDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultasDocenteActionPerformed
        //Abre el formulario de la Informacion que proviene de una Consulta del docente en su menú correspondiente
        new Consulta().setVisible(true);
    }//GEN-LAST:event_menuItemConsultasDocenteActionPerformed

    private void menuItemPerfilDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPerfilDocenteActionPerformed
        // Abre el formulario de la información del perfil profesional del docente.
        new Perfil().setVisible(true);
    }//GEN-LAST:event_menuItemPerfilDocenteActionPerformed

    private void mnuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSalirActionPerformed
        // Salir de la aplicación
        int confirma = JOptionPane.showConfirmDialog(rootPane,"¿Estás seguro que deseas salir?,AMADEO COPORO QUINTANA,DS-DPO2-2102-B1-001",
                                     "Actividad Complementaria",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
       if(JOptionPane.OK_OPTION==confirma){
        System.exit(0);  //cierra todo el sistema. 
       }
       else if(JOptionPane.CANCEL_OPTION==confirma){ //si no así se va a quedar. 
        return;   
       }
    }//GEN-LAST:event_mnuItemSalirActionPerformed

    private void mnuItemAltasAlumnadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAltasAlumnadoActionPerformed
        //Para acceder al formulario de alta de alumnos 
        new AltasAlumnos().setVisible(true);
    }//GEN-LAST:event_mnuItemAltasAlumnadoActionPerformed

    private void mnuItemBajasAlumnadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBajasAlumnadoActionPerformed
        // Para acceder al formulario de baja de alumnos 
        new BajasAlumnos().setVisible(true);
    }//GEN-LAST:event_mnuItemBajasAlumnadoActionPerformed

    private void menuItemAltasDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAltasDocenteActionPerformed
        // Abre el formulario Alta Docente
        new AltasDocente().setVisible(true);
    }//GEN-LAST:event_menuItemAltasDocenteActionPerformed

    private void menuItemConsultaAlumnadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaAlumnadoActionPerformed
         // Para acceder al formulario de consulta de alumnos 
        new ConsultasAlumnos().setVisible(true);
    }//GEN-LAST:event_menuItemConsultaAlumnadoActionPerformed

    private void menuItemBajasDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBajasDocenteActionPerformed
        //  Para acceder al formulario de baja de alumnos
        new BajasDocentes().setVisible(true);
    }//GEN-LAST:event_menuItemBajasDocenteActionPerformed

    private void mnuItemModAlumnadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemModAlumnadoActionPerformed
        //  Para acceder al formulario de modificación de datos de los alumnos
        new ModificacionesAlumnado().setVisible(true);
    }//GEN-LAST:event_mnuItemModAlumnadoActionPerformed

    private void mnuItemModDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemModDocenteActionPerformed
        // Para acceder al formulario de modificación de datos de los docentes
        new ModificacionesDocente().setVisible(true);
    }//GEN-LAST:event_mnuItemModDocenteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspecialidadesMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspecialidadesMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspecialidadesMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspecialidadesMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspecialidadesMedicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuItemAltasDocente;
    private javax.swing.JMenuItem menuItemBajasDocente;
    private javax.swing.JMenuItem menuItemConsultaAlumnado;
    private javax.swing.JMenuItem menuItemConsultasDocente;
    private javax.swing.JMenuItem menuItemPerfilDocente;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu mnuAdministrativo;
    private javax.swing.JMenu mnuAlumnos;
    private javax.swing.JMenuItem mnuBajasMaterias;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenu mnuDatosPersonales;
    private javax.swing.JMenu mnuEstudios;
    private javax.swing.JMenuItem mnuItemAltasAlumnado;
    private javax.swing.JMenuItem mnuItemAltasMaterias;
    private javax.swing.JMenuItem mnuItemBajasAlumnado;
    private javax.swing.JMenuItem mnuItemBecas;
    private javax.swing.JMenuItem mnuItemModAlumnado;
    private javax.swing.JMenuItem mnuItemModDocente;
    private javax.swing.JMenuItem mnuItemPlanEstudios;
    private javax.swing.JMenuItem mnuItemProfesional;
    private javax.swing.JMenuItem mnuItemSalir;
    // End of variables declaration//GEN-END:variables
}
